CreateUsersTable: create table `users` (`id` bigint unsigned not null auto_increment primary key, `first_name` varchar(255) not null, `prefix` varchar(255) not null, `last_name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `active` tinyint(1) not null default '1', `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CreateTelescopeEntriesTable: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` longtext not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateTelescopeEntriesTable: alter table `telescope_entries` add unique `telescope_entries_uuid_unique`(`uuid`)
CreateTelescopeEntriesTable: alter table `telescope_entries` add index `telescope_entries_batch_id_index`(`batch_id`)
CreateTelescopeEntriesTable: alter table `telescope_entries` add index `telescope_entries_family_hash_index`(`family_hash`)
CreateTelescopeEntriesTable: alter table `telescope_entries` add index `telescope_entries_created_at_index`(`created_at`)
CreateTelescopeEntriesTable: alter table `telescope_entries` add index `telescope_entries_type_should_display_on_index_index`(`type`, `should_display_on_index`)
CreateTelescopeEntriesTable: create table `telescope_entries_tags` (`entry_uuid` char(36) not null, `tag` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateTelescopeEntriesTable: alter table `telescope_entries_tags` add index `telescope_entries_tags_entry_uuid_tag_index`(`entry_uuid`, `tag`)
CreateTelescopeEntriesTable: alter table `telescope_entries_tags` add index `telescope_entries_tags_tag_index`(`tag`)
CreateTelescopeEntriesTable: alter table `telescope_entries_tags` add constraint `telescope_entries_tags_entry_uuid_foreign` foreign key (`entry_uuid`) references `telescope_entries` (`uuid`) on delete cascade
CreateTelescopeEntriesTable: create table `telescope_monitoring` (`tag` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateFailedJobsTable: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateFailedJobsTable: alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`)
CreatePersonalAccessTokensTable: create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePersonalAccessTokensTable: alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`)
CreatePersonalAccessTokensTable: alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`)
LaratrustSetupTables: create table `roles` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `display_name` varchar(255) null, `description` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
LaratrustSetupTables: alter table `roles` add unique `roles_name_unique`(`name`)
LaratrustSetupTables: create table `permissions` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `display_name` varchar(255) null, `description` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
LaratrustSetupTables: alter table `permissions` add unique `permissions_name_unique`(`name`)
LaratrustSetupTables: create table `role_user` (`role_id` bigint unsigned not null, `user_id` bigint unsigned not null, `user_type` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
LaratrustSetupTables: alter table `role_user` add constraint `role_user_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade on update cascade
LaratrustSetupTables: alter table `role_user` add primary key `role_user_user_id_role_id_user_type_primary`(`user_id`, `role_id`, `user_type`)
LaratrustSetupTables: create table `permission_user` (`permission_id` bigint unsigned not null, `user_id` bigint unsigned not null, `user_type` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
LaratrustSetupTables: alter table `permission_user` add constraint `permission_user_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade on update cascade
LaratrustSetupTables: alter table `permission_user` add primary key `permission_user_user_id_permission_id_user_type_primary`(`user_id`, `permission_id`, `user_type`)
LaratrustSetupTables: create table `permission_role` (`permission_id` bigint unsigned not null, `role_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
LaratrustSetupTables: alter table `permission_role` add constraint `permission_role_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade on update cascade
LaratrustSetupTables: alter table `permission_role` add constraint `permission_role_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade on update cascade
LaratrustSetupTables: alter table `permission_role` add primary key `permission_role_permission_id_role_id_primary`(`permission_id`, `role_id`)
CreateStudentsTable: create table `students` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `address` varchar(255) not null, `city` varchar(255) not null, `postal_code` varchar(255) not null, `lessons_to_go` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateStudentsTable: alter table `students` add constraint `students_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade
CreateInstructorsTable: create table `instructors` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not null, `address` varchar(255) not null, `city` varchar(255) not null, `postal_code` varchar(255) not null, `description` varchar(255) null, `image` varchar(255) null default '') default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateInstructorsTable: alter table `instructors` add constraint `instructors_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade
CreateLessonsTable: create table `lessons` (`id` bigint unsigned not null auto_increment primary key, `instructor_id` bigint unsigned not null, `student_id` bigint unsigned not null, `pickup_address` varchar(255) not null, `pickup_postal_code` varchar(6) not null, `pickup_city` varchar(255) not null, `goal` varchar(255) not null, `start_date` datetime not null, `end_date` datetime not null, `result` varchar(255) null, `comment` varchar(255) null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateLessonsTable: alter table `lessons` add constraint `lessons_instructor_id_foreign` foreign key (`instructor_id`) references `instructors` (`id`) on delete cascade
CreateLessonsTable: alter table `lessons` add constraint `lessons_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade
CreateExamsTable: create table `exams` (`id` bigint unsigned not null auto_increment primary key, `student_id` bigint unsigned not null, `pickup_address` varchar(255) not null, `pickup_postal_code` varchar(6) not null, `pickup_city` varchar(255) not null, `goal` varchar(255) not null, `start_date` datetime not null, `end_date` datetime not null, `result` varchar(255) null, `comment` varchar(255) null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateExamsTable: alter table `exams` add constraint `exams_student_id_foreign` foreign key (`student_id`) references `students` (`id`) on delete cascade
CreateModificationsTable: create table `modifications` (`id` bigint unsigned not null auto_increment primary key, `lesson_id` bigint unsigned not null, `pickup_address` varchar(255) not null, `pickup_postal_code` varchar(6) not null, `pickup_city` varchar(255) not null, `specialty` enum('0', '1') not null default '0') default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateModificationsTable: alter table `modifications` add constraint `modifications_lesson_id_foreign` foreign key (`lesson_id`) references `lessons` (`id`) on delete cascade
CreateCarsTable: create table `cars` (`id` bigint unsigned not null auto_increment primary key, `type` varchar(255) not null, `brand` varchar(255) not null, `model` varchar(255) not null, `license_plate` varchar(255) not null, `image` varchar(255) not null default '', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateContactTable: create table `contact` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `subject` varchar(255) not null, `message` varchar(255) not null, `answer` varchar(255) null, `done` enum('0', '1') not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateNotificationsTable: create table `notifications` (`id` bigint unsigned not null auto_increment primary key, `role` varchar(255) not null, `title` varchar(255) not null, `notification` text not null, `created_at` timestamp null, `updated_at` timestamp null, `valid_until` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
